//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kulva.KulvaSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.elisa.fi/kulva", ConfigurationName="KulvaSvc.IKulva")]
    public interface IKulva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elisa.fi/kulva/IKulva/Stamp", ReplyAction="http://www.elisa.fi/kulva/IKulva/StampResponse")]
        string Stamp(string clientId, string deviceId, string cardId, string reasonCode, System.DateTime occurredTime, System.Nullable<System.DateTime> endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elisa.fi/kulva/IKulva/Stamp", ReplyAction="http://www.elisa.fi/kulva/IKulva/StampResponse")]
        System.Threading.Tasks.Task<string> StampAsync(string clientId, string deviceId, string cardId, string reasonCode, System.DateTime occurredTime, System.Nullable<System.DateTime> endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elisa.fi/kulva/IKulva/HeartBeat", ReplyAction="http://www.elisa.fi/kulva/IKulva/HeartBeatResponse")]
        bool HeartBeat(string clientId, string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elisa.fi/kulva/IKulva/HeartBeat", ReplyAction="http://www.elisa.fi/kulva/IKulva/HeartBeatResponse")]
        System.Threading.Tasks.Task<bool> HeartBeatAsync(string clientId, string deviceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKulvaChannel : Kulva.KulvaSvc.IKulva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KulvaClient : System.ServiceModel.ClientBase<Kulva.KulvaSvc.IKulva>, Kulva.KulvaSvc.IKulva {
        
        public KulvaClient() {
        }
        
        public KulvaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KulvaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KulvaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KulvaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Stamp(string clientId, string deviceId, string cardId, string reasonCode, System.DateTime occurredTime, System.Nullable<System.DateTime> endTime) {
            return base.Channel.Stamp(clientId, deviceId, cardId, reasonCode, occurredTime, endTime);
        }
        
        public System.Threading.Tasks.Task<string> StampAsync(string clientId, string deviceId, string cardId, string reasonCode, System.DateTime occurredTime, System.Nullable<System.DateTime> endTime) {
            return base.Channel.StampAsync(clientId, deviceId, cardId, reasonCode, occurredTime, endTime);
        }
        
        public bool HeartBeat(string clientId, string deviceId) {
            return base.Channel.HeartBeat(clientId, deviceId);
        }
        
        public System.Threading.Tasks.Task<bool> HeartBeatAsync(string clientId, string deviceId) {
            return base.Channel.HeartBeatAsync(clientId, deviceId);
        }
    }
}
